### PR TITLE
fix: pin `colors` to `1.4.0`

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
https://snyk.io/blog/open-source-maintainer-pulls-the-plug-on-npm-packages-colors-and-faker-now-what

### CODE REVIEW

**Comment by XhmikosR** [comment]
@rafeca: could you merge this and cut a new patch version please?

**Comment by jerome-yvan** [comment]
hi, please merge and release the new patch.

**Comment by rafeca** [comment]
Thanks for the fix, i’ll release a new version later today when i get home

**Comment by fbartho** [comment]
Is there a long-term fix for this colors issue? I believe we need to remove the `colors` dep and switch to a different one.

**Comment by DABH** [comment]
Please see https://github.com/rafeca/prettyjson/pull/60 -- thanks all! :)

**Pull request merged**
